// Code generated by protoc-gen-go. DO NOT EDIT.
// source: enums.proto

/*
Package media_manager is a generated protocol buffer package.

It is generated from these files:
	enums.proto
	fileslist.proto
	message.proto
	unrar.proto

It has these top-level messages:
	FilesListRequest
	FilesListResponse
	Request
	Response
	UnrarRequest
	UnrarResponse
*/
package media_manager

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Location int32

const (
	Location_UNKNOWN   Location = 0
	Location_DOWNLOADS Location = 1
	Location_STAGING   Location = 2
)

var Location_name = map[int32]string{
	0: "UNKNOWN",
	1: "DOWNLOADS",
	2: "STAGING",
}
var Location_value = map[string]int32{
	"UNKNOWN":   0,
	"DOWNLOADS": 1,
	"STAGING":   2,
}

func (x Location) String() string {
	return proto.EnumName(Location_name, int32(x))
}
func (Location) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterEnum("media_manager.Location", Location_name, Location_value)
}

func init() { proto.RegisterFile("enums.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xcd, 0x2b, 0xcd,
	0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xcd, 0x4d, 0x4d, 0xc9, 0x4c, 0x8c, 0xcf,
	0x4d, 0xcc, 0x4b, 0x4c, 0x4f, 0x2d, 0xd2, 0x32, 0xe6, 0xe2, 0xf0, 0xc9, 0x4f, 0x4e, 0x2c, 0xc9,
	0xcc, 0xcf, 0x13, 0xe2, 0xe6, 0x62, 0x0f, 0xf5, 0xf3, 0xf6, 0xf3, 0x0f, 0xf7, 0x13, 0x60, 0x10,
	0xe2, 0xe5, 0xe2, 0x74, 0xf1, 0x0f, 0xf7, 0xf3, 0xf1, 0x77, 0x74, 0x09, 0x16, 0x60, 0x04, 0xc9,
	0x05, 0x87, 0x38, 0xba, 0x7b, 0xfa, 0xb9, 0x0b, 0x30, 0x25, 0xb1, 0x81, 0x8d, 0x32, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x1a, 0x04, 0x6b, 0xb6, 0x59, 0x00, 0x00, 0x00,
}
